# Generated by Django 5.1.2 on 2024-10-23 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400, unique=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificada')),
            ],
            options={
                'verbose_name': 'Acerca de',
                'verbose_name_plural': 'Acerca de',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CtgPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Categoría')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EtqPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Etiqueta')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificada')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Key Link')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Red Social')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='Enlace')),
                ('icon', models.CharField(blank=True, max_length=400, null=True, unique=True, verbose_name='Icono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificada')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['-created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('excerpt', models.TextField(verbose_name='Bajada')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posteos', verbose_name='Imagen')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_4_author', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_4_categories', to='A05Blo.ctgpost', verbose_name='Categoría')),
                ('tags', models.ManyToManyField(to='A05Blo.etqpost', verbose_name='Etiqueta')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created'],
            },
        ),
    ]
