# Generated by Django 5.1.2 on 2024-10-30 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Isapre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Isapre',
                'verbose_name_plural': 'Isapres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/img_no_disp.png', upload_to='usuarios')),
                ('dni', models.CharField(blank=True, max_length=10, null=True)),
                ('nacim', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(help_text='Usuario con perfil de funcionario', on_delete=django.db.models.deletion.RESTRICT, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'A01Aeg_Funcionario',
                'ordering': ['-created', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/img_no_disp.png', upload_to='usuarios')),
                ('dni', models.CharField(blank=True, max_length=10, null=True)),
                ('nacim', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('experiencia', models.TextField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(help_text='Usuario con perfil de médico', on_delete=django.db.models.deletion.RESTRICT, related_name='medico', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'ordering': ['-created', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/img_no_disp.png', upload_to='usuarios')),
                ('dni', models.CharField(blank=True, max_length=10, null=True)),
                ('nacim', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True)),
                ('grupoSangre', models.CharField(blank=True, choices=[('1', '0-'), ('2', '0+'), ('3', 'A-'), ('4', 'A+'), ('5', 'B-'), ('6', 'B+'), ('7', 'AB-'), ('8', 'AB+'), ('9', 'Otro')], max_length=4, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'Sin actividad'), ('1', 'Con hora tomada'), ('2', 'Exámenes pendientes'), ('3', 'Diagnosticado')], default=0, max_length=20, null=True)),
                ('salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='A01Seg.isapre')),
                ('user', models.OneToOneField(help_text='Usuario con perfil de paciente', on_delete=django.db.models.deletion.RESTRICT, related_name='paciente', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created', 'user'],
            },
        ),
    ]
