# Generated by Django 5.1.2 on 2024-11-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A01Seg', '0002_medico_estado_alter_funcionario_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='estado',
            field=models.CharField(blank=True, choices=[('0', 'No activo'), ('1', 'Activo'), ('2', 'Vacaciones')], default=1, max_length=20, null=True),
        ),
    ]
