# Generated by Django 5.1.2 on 2024-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A01Seg', '0003_alter_medico_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cirugPrev',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contacto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfPrev',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
