# Generated by Django 5.1.2 on 2024-11-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A01Seg', '0004_paciente_cirugprev_paciente_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cirugPrev',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contacto',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfPrev',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
