# Generated by Django 5.1.2 on 2024-11-03 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('A01Seg', '0003_alter_medico_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('presion', models.CharField(max_length=10, verbose_name='Presión Arterial')),
                ('altura', models.CharField(max_length=10, verbose_name='Altura (cm)')),
                ('sintomas', models.TextField(max_length=500, verbose_name='Sintomatología')),
                ('evaPre', models.TextField(max_length=500, verbose_name='Evaluación Preliminar')),
                ('diagnosis', models.TextField(max_length=500, verbose_name='Diagnósis')),
                ('posologia', models.TextField(max_length=500, verbose_name='Posología')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='A01Seg.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='A01Seg.paciente')),
            ],
            options={
                'verbose_name': 'Ficha De Paciente',
                'verbose_name_plural': 'Fichas Del Paciente',
                'ordering': ['id'],
            },
        ),
    ]
