# Generated by Django 5.1.2 on 2024-11-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A04Fic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichapaciente',
            name='presion',
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='diastole',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Presión Diastólica'),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='motivo',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Motivo de Consulta'),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='notas',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Notas del Médico'),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='sistole',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Presión Sistólica'),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='altura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='diagnosis',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Diagnósis'),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='evaPre',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Evaluación Preliminar'),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='posologia',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Tratamiento y Posología'),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='sintomas',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Sintomatología'),
        ),
    ]
