# Generated by Django 5.1.2 on 2024-11-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A04Fic', '0002_remove_fichapaciente_presion_fichapaciente_diastole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichapaciente',
            name='diast',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='hei_cm',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='sist',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='temp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='wei_gr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
