# Generated by Django 5.1.2 on 2024-11-06 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A01Seg', '0003_alter_medico_estado'),
        ('A04Fic', '0003_fichapaciente_diast_fichapaciente_hei_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichapaciente',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medicos', to='A01Seg.medico'),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fichas', to='A01Seg.paciente'),
        ),
    ]
